### PR TITLE
chore: update go package dependencies for demo

### PR DESCRIPTION
**Pull request by rphmeier**

### CODE REVIEW

**Comment by rphmeier** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #158** <a href="https://app.graphite.dev/github/pr/thrumdev/blobs/158?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/thrumdev/blobs/158?utm_source=stack-comment).

**Comment by rphmeier** [comment]
I could not get `ignite chain build` to work until these packages were updated with `go get`.

**Comment by pepyakin** [comment]
When I run `go get` locally:

under root:

go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

under demo/rollkit/

go: no package to get in current directory

that said, `ignite chain build` continues to work with this PR.

**Comment by rphmeier** [comment]
> go version go1.21.5 darwin/arm64

most recent release. I've never used go before so no idea what's going on

**Pull request merged**
