### PR TITLE
rename to ikura

### PR DESCRIPTION
**Pull request by gabriele-0201**
Here's the renaming of every `sugondat` to `ikura`. The only place where I left `sugondat` is the `protocol-id` of the Kusama chain spec.

There are a couple of open questions: should the command to build the specs be "sugondat-kusama" or "ikura-kusama"? And the runtime? Should it be "kusama-runtime" or "sugondat-kusama"? For now, both are renamed to `ikura`!

TODOs:
+ [x] Generate new subxt
+ [x] Tests

### CODE REVIEW

**Comment by gabriele-0201** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #230** <a href="https://app.graphite.dev/github/pr/thrumdev/blobs/230?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/thrumdev/blobs/230?utm_source=stack-comment).

**Comment by pepyakin** [comment]
We could make it ikura-kusama. At the same time, maybe an alias for sugondat-kusama would also be good.

**Comment by gabriele-0201** [comment]
It has been updated to 'gondatsu-kusama'

**Comment by rphmeier** [comment]
> It has been updated to 'gondatsu-kusama'

This is redundant and it should just be gondatsu

**Pull request merged**
